from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

def create_pdf(question, answer):
    filename = "AI_Response.pdf"
    pdf = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()
    content = []

    title = Paragraph(
        "AI_Assistant - Response Report", 
        styles["Title"]
    )
    content.append(title)

    content.append(Spacer(1, 20))


    content.append(
        Paragraph(
            f"<b>Question:</b><br/>{question}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 15))


    content.append(
        Paragraph(
            "<b>AI Response:</b>",
            styles["Heading2"]
        )
    )


    for line in answer.split("\n"):

        content.append(
            Paragraph(
                line,
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 20)
        )


    content.append(
       Paragraph(
        f"""
        Generated by AI Assistant<br/>
        Developed by Td Kris <br/>
         Generated on: {datetime.now()}
        """,
        styles["Normal"]
        )
    )


    pdf.build(content)


    return filename